"""Shared operational limits for PSP and API validation."""

PSP_MAX_CAPACITY_MWH = 450.0
PSP_MIN_CAPACITY_MWH = 10.0
PSP_DEFAULT_CAPACITY_MWH = 360.0

PSP_DEFAULT_MAX_CHARGE_MW = 60.0
PSP_DEFAULT_MAX_DISCHARGE_MW = 50.0
PSP_DEFAULT_MIN_DISPATCH_MW = 6.0
PSP_MAX_CHARGE_MW = 100.0
PSP_MAX_DISCHARGE_MW = 100.0
PSP_MAX_MIN_DISPATCH_MW = 60.0